version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-16-may-2021/motion-backend/team-5:master
    env_file:
      - .env/prod.env
    command: "sh /scripts/run.sh"
    volumes:
    - static-files:/static-files
    - media-files:/media-files
    - frontend:/frontend/build
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    env_file:
      - .env/prod.env
    volumes:
    - postgres_volume:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/master.conf:/etc/nginx/conf.d/master.conf
      - static-files:/static-files
      - media-files:/media-files
      - /etc/letsencrypt:/etc/letsencrypt
      - frontend:/frontend


volumes:
  postgres_volume:
  static-files:
  media-files:
  frontend: